config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class = row>
        <h1 class="text-center">Contact Form</h1>
        
        <div class="col-md-4 offset-md-4">
            <div class="well"
                <%= form_for "/contacts" do |f| %>
                    <div class="mb-3">
                        <%= f.label :name, class: 'form-label' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    
                    <div class="mb-3">
                        <%= f.label :email, class: 'form-label' %>
                        <%= f.text_field :email, class: 'form-control' %>
                    </div>
                    
                    <div class="mb-3">
                        <%= f.label :comments, class: 'form-label' %>
                        <%= f.text_area :comments, class: 'form-control' %>
                    </div>
                    
                    <%= f.submit 'Submit', class: 'btn btn-primary' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Valorant Duo Matcher</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to "/", class: "navbar-brand" do %>
          <i>Valorant Duo Matcher</i>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link acitve" do %>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link" do %>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_contact_path, class: "nav-link" do %>
                Contact Us
              <% end %>
            </li>
          </ul>
          <ul class="navbar-nav nav-account me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "/log_in", class: "nav-link" do %>
                Log In
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/sign_up", class: "nav-link" do %>
                Sign Up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/guest", class: "nav-link" do %>
                Guest
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
  
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>Welcome to Valorant Duo Matcher! This site was created as a place where
    Valorant players could quickly match up with other players to queue
    competitive games with. Feel free to make an account or proceed as a guest
    as you try to find a good match for you.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Valorant Duo Matcher</h1>
    <p>
        Find the duo partner of your dreams.
    </p>
    <br />
  </div>
</div>

<div class="container home_table">
  <div class="row">
    <div class="col-md-4 home_table_header">
      <h4>
        Already have an account? Log in below:
      </h4>
    </div>
    <div class="col-md-4 home_table_header">
      <h4>
        Creat a new account here:
      </h4>
    </div>
    <div class="col-md-4 home_table_header">
      <h4>
        No account necessary. Proceed as a guest below:
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Log In »</a>
      </p>
    </div>
    <div class="col-md-4">
      <p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Sign Up »</a>
      </p>
    </div>
    <div class="col-md-4">
      <p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Proceed As Guest »</a>
      </p>
    </div>
  </div>
</div>